# answers.py
correct_answers = {
    # ==================== COUNTER-STRIKE (21 задание) ====================
    ("cs", 1): [
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "1345", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "1", "points": 1, "explanation": ""},
        {"answer": "4", "points": 2, "explanation": "Задание на 2 балла"},
        {"answer": "45", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "3", "points": 2, "explanation": "Задание на 2 балла"},
        {"answer": "1123", "points": 2, "explanation": "Задание на 2 балла"},
        {"answer": "1", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "3124", "points": 1, "explanation": ""},
        {"answer": "1", "points": 1, "explanation": ""},
        {"answer": "352", "points": 1, "explanation": ""},
        {"answer": "1", "points": 2, "explanation": "Задание на 2 балла"},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "4", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
    ],

    # ==================== MINECRAFT (25 заданий) ====================
    ("minecraft", 1): [
        {"answer": "4", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "1", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "4", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "4", "points": 1, "explanation": ""},
        {"answer": "46", "points": 1, "explanation": ""},
        {"answer": "1", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
        {"answer": "8", "points": 1, "explanation": ""},
        {"answer": "10050", "points": 1, "explanation": ""},
        {"answer": "1", "points": 1, "explanation": ""},
        {"answer": "1", "points": 1, "explanation": ""},
        {"answer": "1", "points": 1, "explanation": ""},
        {"answer": "3", "points": 1, "explanation": ""},
        {"answer": "2", "points": 1, "explanation": ""},
    ],
}